name: CI_Tests

on:
  push:
    branches:
      - 'main'
      - 'release-'
    tags: '*'
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1]
        julia-arch: [x86]
        os: [ubuntu-latest]
    steps:
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}

      - uses: actions/checkout@v1
      - uses: julia-actions/julia-buildpkg@latest
      - name: Install AEPclass
        run: |
          julia --project=test -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - name: Run Build 1
        run: |
          julia --project=test test/runtests_1.jl
      - name: Run Build 2
        run: |
          julia --project=test test/runtests_2.jl
      - name: Run Build 3
        run: |
          julia --project=test test/runtests_3.jl
      - name: Run Build 4
        run: |
          julia --project=test test/runtests_4.jl
      - name: Run Build 5
        run: |
          julia --project=test test/runtests_5.jl
      - name: Run Build 6
        run: |
          julia --project=test test/runtests_6.jl
      - name: Run Build 7
        run: |
          julia --project=test test/runtests_7.jl
      - name: Run Build 8
        run: |
          julia --project=test test/runtests_8.jl
      - name: Run Build 9
        run: |
          julia --project=test test/runtests_9.jl
      - name: Run Build 10
        run: |
          julia --project=test test/runtests_10.jl
      - name: Run Build 11
        run: |
          julia --project=test test/runtests_11.jl
      - name: Run Build 12
        run: |
          julia --project=test test/runtests_12.jl
      - name: Run Build 13
        run: |
          julia --project=test test/runtests_13.jl
