name: CI_Tests

on:
  push:
    branches:
      - 'main'
      - 'release-'
    tags: '*'
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1]
        julia-arch: [x86]
        os: [ubuntu-latest]
    steps:
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}

      - uses: actions/checkout@v1
      - uses: julia-actions/julia-buildpkg@latest
      - name: Install AEPclass
        run: |
          julia --project=test -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - name: Run Build 1
        run: |
          julia --project=test test/runtests_1.jl
      - name: Run Build 2
        run: |
          julia --project=test test/runtests_2.jl
